name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Installer les dépendances
        run: pip install -r requirements.txt
      - name: Lancer les tests
        run: pytest
      - name: Générer la couverture
        run: pytest --cov=src/bibliotheque --cov-report=term-missing
